{% set name = "Janome" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  https://pypi.io/packages/source/j/janome/Janome-0.4.1.tar.gz
  sha256: 6c2c38d894014d57cb3151265c11146506ead3b3bc290898adc33711711612de

build:
  number: 6
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - janome
    - janome.sysdic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mocobeta/janome
  summary: Japanese morphological analysis engine.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt
  doc_url: https://mocobeta.github.io/janome/en/
  dev_url: https://github.com/mocobeta/janome/wiki#for-contributors

extra:
  recipe-maintainers:
    - BastianZim
